language: ruby
rvm:
- 2.1
# Assume bundler is being used, install step will run `bundle install`.
install:
- bundle install
#script: jekyll build && htmlproof ./_site
script: rake test

# branch whitelist
branches:
  only:
  - master     # test the master branch

env:
  global:


addons:
  code_climate:
    repo_token: 9b5f2b8c8eb1bb3d1f8cdc5c27964617787e896cd0a07ceb1a047518d731e7e8
